/*
 * BiMasa Backend APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CategoryCreateRequest : IEquatable<CategoryCreateRequest>
    { 
        /// <summary>
        /// Gets or Sets ImageData
        /// </summary>
        [DataMember(Name="imageData")]
        public string ImageData { get; set; }

        /// <summary>
        /// Gets or Sets ParentId
        /// </summary>
        [DataMember(Name="parentId")]
        public Guid? ParentId { get; set; }

        /// <summary>
        /// Gets or Sets ClientId
        /// </summary>
        [DataMember(Name="clientId")]
        public Guid? ClientId { get; set; }

        /// <summary>
        /// Gets or Sets CategoryTranslations
        /// </summary>
        [DataMember(Name="categoryTranslations")]
        public List<CategoryTranslationDTO> CategoryTranslations { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CategoryCreateRequest {\n");
            sb.Append("  ImageData: ").Append(ImageData).Append("\n");
            sb.Append("  ParentId: ").Append(ParentId).Append("\n");
            sb.Append("  ClientId: ").Append(ClientId).Append("\n");
            sb.Append("  CategoryTranslations: ").Append(CategoryTranslations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CategoryCreateRequest)obj);
        }

        /// <summary>
        /// Returns true if CategoryCreateRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of CategoryCreateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CategoryCreateRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ImageData == other.ImageData ||
                    ImageData != null &&
                    ImageData.Equals(other.ImageData)
                ) && 
                (
                    ParentId == other.ParentId ||
                    ParentId != null &&
                    ParentId.Equals(other.ParentId)
                ) && 
                (
                    ClientId == other.ClientId ||
                    ClientId != null &&
                    ClientId.Equals(other.ClientId)
                ) && 
                (
                    CategoryTranslations == other.CategoryTranslations ||
                    CategoryTranslations != null &&
                    CategoryTranslations.SequenceEqual(other.CategoryTranslations)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ImageData != null)
                    hashCode = hashCode * 59 + ImageData.GetHashCode();
                    if (ParentId != null)
                    hashCode = hashCode * 59 + ParentId.GetHashCode();
                    if (ClientId != null)
                    hashCode = hashCode * 59 + ClientId.GetHashCode();
                    if (CategoryTranslations != null)
                    hashCode = hashCode * 59 + CategoryTranslations.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CategoryCreateRequest left, CategoryCreateRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CategoryCreateRequest left, CategoryCreateRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
